name: jtech_base
description: "jtech project base library"
version: 0.3.4
homepage: https://www.jtech.com

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.7.0
  path: ^1.9.0
  intl: ^0.19.0
  logger: ^2.4.0
  crypto: ^3.0.6
  provider: ^6.1.2
  objectbox: ^4.0.3
  go_router: ^14.3.0
  http_parser: ^4.0.2
  file_picker: ^8.1.3
  fluttertoast: ^8.2.8
  easy_refresh: ^3.4.0
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  flex_color_scheme: ^7.3.1
  package_info_plus: ^8.1.0
  shared_preferences: ^2.3.2
  permission_handler: ^11.3.1
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  objectbox_flutter_libs: ^4.0.3
  loading_animation_widget: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/to/asset-from-package
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/to/resolution-aware-images

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/to/font-from-package
